version: '3.5'

services:
  redis:
    image: redis:7.0-alpine
    command: redis-server --requirepass developer

    ports:
      - "6379:6379"
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
  dev:
    image: hikari-api-app
    build: .
    depends_on:
      - redis
      - db
    command: yarn dev
    env_file:
      - .env
    links:
      - redis
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/hikari-api-app
      - node_modules:/node_modules
volumes:
  node_modules: {}
